### ISSUE TITLE
[2pt] Set up Reservations

### ISSUE THREAD

**Issue by badger-99** [badger-99/workspace-reservation-back-end#5]
- Create a table for reservations with the following columns, none of which can be null:
  - City
  - Start Date
  - End Date (Will be same as start date if reserving only one day)
  - User_ID (KF)
  - Workspace_ID (FK)

- Create a model for reservations.
  - Set a ‘belongs to’ relationship with User and Workspace.
  - Set two unique indices, the first one for the city, workspace_id, and start date columns, and the second one for the city, workspace_id, and end date columns
  - All columns must be validated and can’t be null

- Create a controller for reservations with the following actions:
  - Index
  - Create
    - Create a DB record with JSON data received from the react app through an API post method

**Comment by wickathou** [comment]
https://github.com/badger-99/workspace-reservation-back-end/pull/13
